import {Component} from '@angular/core';
import {RouterLink, ActivatedRoute} from '@angular/router';
import {NgFor} from '@angular/common';

type Solution={eyebrow:string;title:string;intro:string;problems:string[];capabilities:string[];example:string};

const solutions:Record<string,Solution>={
 'business-systems':{eyebrow:'01 • BUSINESS SYSTEMS',title:'Bring the operational pieces into one controlled system.',intro:'Replace scattered spreadsheets, email threads and disconnected records with software built around how your team actually works.',problems:['Information spread across spreadsheets and messages','Different users needing different access','Manual approvals and follow-ups','Limited visibility into day-to-day operations'],capabilities:['Role-based access and user management','Records, statuses and workflow states','Approval queues and operational dashboards','Search, reporting and audit trails','Notifications and automated follow-ups'],example:'A request-driven business can move from email and spreadsheets to a system where requests are submitted, assigned, approved, tracked and reported from one place.'},
 'customer-portals':{eyebrow:'02 • CUSTOMER PORTALS',title:'Give customers a clear place to get things done.',intro:'Create secure self-service experiences that reduce back-and-forth while giving customers visibility over their information and progress.',problems:['Customers relying on email or phone for updates','Repeated manual data capture','No clear status or document visibility','Staff spending time answering routine requests'],capabilities:['Registration and secure authentication','Customer profiles and information management','Requests, submissions and document uploads','Status tracking and notifications','Self-service account and communication areas'],example:'A service business can give customers a portal to register, submit a request, upload documents and follow progress without relying on a chain of emails.'},
 'workflow-automation':{eyebrow:'03 • WORKFLOW AUTOMATION',title:'Turn repetitive handoffs into controlled digital workflows.',intro:'Make business rules visible in software so work moves between people, systems and stages without unnecessary manual intervention.',problems:['Tasks handed between teams manually','Approvals lost in email or chat','Repeated data entry and notifications','Reconciliation and exception handling done by hand'],capabilities:['Workflow states and business rules','Automated notifications and reminders','Approvals and escalation paths','Scheduled and background processing','Reconciliation and exception workflows'],example:'A multi-step approval process can become a trackable workflow with defined states, responsible users, automatic notifications and an auditable history.'},
 'payments-integrations':{eyebrow:'04 • PAYMENTS & INTEGRATIONS',title:'Connect the systems your workflow depends on.',intro:'Integrate payments, identity services, APIs and data platforms so important business processes can move between systems reliably.',problems:['Systems that do not share information','Manual payment confirmation','Third-party services handled inconsistently','Data duplicated across platforms'],capabilities:['Payment provider integrations','Identity and verification services','REST APIs and webhooks','Database and third-party integrations','Retries, reconciliation and integration logging'],example:'A transaction platform can connect identity verification, payment processing, notifications and its own database into one controlled customer journey.'},
 'mobile-applications':{eyebrow:'05 • MOBILE APPLICATIONS',title:'Take the workflow where the work actually happens.',intro:'Focused mobile experiences can extend business processes to customers and operational teams working away from a desk.',problems:['Desk-based systems do not fit field work','Teams relying on calls and messages','Limited visibility while away from the office','Customers needing mobile-first interactions'],capabilities:['Customer and staff mobile experiences','Task and job updates','Location and operational data','Notifications and status changes','API-connected mobile workflows'],example:'A field operation can give its teams a focused mobile interface for receiving work, updating progress, recording information and keeping the central system current.'},
 'modernisation':{eyebrow:'06 • MODERNISATION',title:'Move fragile systems forward without losing what works.',intro:'Modernisation does not always mean starting again. The right approach can progressively replace fragile technology while preserving valuable business knowledge and workflows.',problems:['Legacy systems becoming difficult to maintain','Disconnected tools creating duplicate work','Old interfaces slowing users down','Critical processes depending on fragile technology'],capabilities:['System and workflow assessment','Incremental replacement','API and integration layers','Data migration and consolidation','Modern web interfaces and maintainable services'],example:'A legacy process can be modernised in stages: preserve the critical workflow, introduce a new interface or service, move data safely, then retire the fragile component when the replacement is ready.'}
};

@Component({standalone:true,imports:[RouterLink,NgFor],template:`
<section class="page-hero solution-hero"><p class="section-kicker">{{solution.eyebrow}}</p><h1>{{solution.title}}</h1><p>{{solution.intro}}</p></section>
<section class="section solution-section"><div class="solution-grid"><div><p class="section-kicker">COMMON PROBLEMS</p><h2>Where this kind of software can help.</h2></div><ul class="solution-list"><li *ngFor="let item of solution.problems">{{item}}</li></ul></div></section>
<section class="section solution-section"><div class="solution-grid"><div><p class="section-kicker">WHAT CAN BE BUILT</p><h2>Capabilities shaped around the workflow.</h2></div><ul class="solution-list"><li *ngFor="let item of solution.capabilities">{{item}}</li></ul></div></section>
<section class="section solution-example"><p class="section-kicker">EXAMPLE</p><h2>{{solution.example}}</h2></section>
<section class="cta"><div><p class="section-kicker">START WITH THE WORKFLOW</p><h2>Have a process like this?</h2><p>Describe what is slow, manual, disconnected or difficult and explore what a software solution could look like.</p></div><a class="button light" routerLink="/contact">Start a conversation →</a></section>
`})
export class SolutionComponent{
 solution:Solution=solutions['business-systems'];
 constructor(route:ActivatedRoute){const slug=route.snapshot.paramMap.get('slug')??'business-systems';this.solution=solutions[slug]??solutions['business-systems'];}
}